### PR TITLE
Added a lot of acronyms, cleaned up file a bit

### PR DESCRIPTION
**Pull request by karlbrown-va**
* Added a number of acronyms from a spreadsheet found on the VA network
* Cleaned up and removed duplicates
* Fixed typos
* Improve `clean.sh` script

### CODE REVIEW

**Comment by karlbrown-va** [comment]
Requesting review from @batemapf

**Comment by batemapf** [comment]
Whoa! This is awesome, thanks for cleaning up!

**Comment by karlbrown-va** [comment]
Hi, sorry I don't see output.csv there - I added it to .gitignore.

**Comment by batemapf** [comment]
🤦‍♂ heh, definitely moving too fast this morning. saw `output.csv` in the `.gitignore` change and read it as adding a file. sorry for the confusion — need to go get some coffee...

**Comment by karlbrown-va** [comment]
Thanks. I don't have write access, could you merge please?

**Pull request merged**
